# Generated by Django 5.2.9 on 2025-12-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=75)),
                ('author', models.CharField(max_length=65, null=True)),
                ('type', models.CharField(choices=[('FIRST_COURSES', 'first courses'), ('SECOND_COURSES', 'second courses'), ('SALADS', 'salads'), ('SNACKS', 'snacks'), ('DESSERTS', 'desserts'), ('BEVERAGES', 'beverages'), ('BAKERY', 'bakery')], default='FIRST_COURSES', max_length=25)),
                ('description', models.TextField(max_length=1500)),
                ('video_uri', models.CharField(max_length=250, null=True)),
                ('ingredients', models.TextField(max_length=350)),
                ('cuisine', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
