# Generated by Django 5.2.9 on 2025-12-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('MALE', 'men'), ('FEMALE', 'woman'), ('UNISEX', 'unisex')], default='MALE', max_length=20)),
                ('type', models.CharField(choices=[('SNEAKERS', 'sneakers'), ('BOOTS', 'boots'), ('FLIP_FLOPS', 'flip-flops'), ('SANDALS', 'sandals'), ('HEELS', 'heels'), ('SLIPPERS', 'slippers'), ('SPORT_SHOES', 'sport shoes'), ('CASUAL', 'casual')], default='SNEAKERS', max_length=20)),
                ('color', models.CharField(choices=[('WHITE', 'white'), ('BLACK', 'black'), ('RED', 'red'), ('BLUE', 'blue'), ('GREEN', 'green'), ('YELLOW', 'yellow'), ('BROWN', 'brown'), ('GREY', 'grey'), ('PINK', 'pink'), ('ORANGE', 'orange'), ('PURPLE', 'purple'), ('BEIGE', 'beige'), ('NAVY', 'navy'), ('SILVER', 'silver'), ('GOLD', 'gold'), ('MULTICOLOR', 'multicolor')], default='WHITE', max_length=30)),
                ('size', models.CharField(choices=[('EXTRA_SMALL', 'XS'), ('SMALL', 'S'), ('MEDIUM', 'M'), ('LARGE', 'L'), ('EXTRA_LARGE', 'XL'), ('DOUBLE_EXTRA_LARGE', 'XXL')], default='MEDIUM', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('manufacture', models.CharField(max_length=75, null=True)),
            ],
        ),
    ]
